version: '3'
services:
  database-service:
    build: ./mySQL
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
  flask-service:
    build: ./flaskApp
    ports:
      - "5001:5001"
      

  # flask-service:
  #   build: ./flaskApp
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - database-service